local ETAdapter = class("ETAdapter")
ETAdapter.TAG = "Brniuniu-ETAdapter"

function ETAdapter:ctor()

    --百人牛牛3倍场
    GameNet._ada._etable[BRNN_CMD.CMD_BR_QUERY_BANKER_LIST_V2]    =  BRNN_ET.UPDATE_DELAR_INFO
    GameNet._ada._etable[BRNN_CMD.USER_LEAVE_SEAT]    =  BRNN_ET.USER_LEAVE_SEAT_EVENT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_ENTER_DESK] =  BRNN_ET.BR_NET_INPUT_GAME_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_USER_SIT_DOWN] =  BRNN_ET.BR_NET_SIT_DOWN_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_BANKER_CHANGE] =  BRNN_ET.BR_NET_BANKER_CHANGE
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_EXIT_DESK] =  BRNN_ET.BR_NET_EXIT_RESPONSE_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_BANKER_EXIT] =  BRNN_ET.BR_NET_EVENT_BANKER_EXIT--百人场通知有人下庄
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_FOLLOW_BET] = BRNN_ET.NET_BR_FOLLOW_BET_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_OPEN_CARDS] =  BRNN_ET.BR_NET_OPEN_SHARE_CARDS_EVT--百人场公共牌
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_BET_START] =  BRNN_ET.BR_NET_EVENT_BET_START--百人场进入下注时间
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_GAME_OVER] = BRNN_ET.BR_NET_EVENT_GAME_OVER

    --百人牛牛10倍场
    GameNet._ada._etable[BRNN_CMD.CMD_BR_QUERY_BANKER_LIST_V10]    =  BRNN_ET.UPDATE_DELAR_INFO
    GameNet._ada._etable[BRNN_CMD.USER_LEAVE_SEAT_V10]    =  BRNN_ET.USER_LEAVE_SEAT_EVENT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_ENTER_DESK_V10] =  BRNN_ET.BR_NET_INPUT_GAME_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_USER_SIT_DOWN_V10] =  BRNN_ET.BR_NET_SIT_DOWN_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_BANKER_CHANGE_V10] =  BRNN_ET.BR_NET_BANKER_CHANGE
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_EXIT_DESK_V10] =  BRNN_ET.BR_NET_EXIT_RESPONSE_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_BANKER_EXIT_V10] =  BRNN_ET.BR_NET_EVENT_BANKER_EXIT--百人场通知有人下庄
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_FOLLOW_BET_V10] = BRNN_ET.NET_BR_FOLLOW_BET_EVT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_OPEN_CARDS_V10] =  BRNN_ET.BR_NET_OPEN_SHARE_CARDS_EVT--百人场公共牌
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_BET_START_V10] =  BRNN_ET.BR_NET_EVENT_BET_START--百人场进入下注时间
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_GAME_OVER_V10] = BRNN_ET.BR_NET_EVENT_GAME_OVER

    GameNet._ada._etable[BRNN_CMD.BR_EVENT_DESK_CHAT_V3] =  BRNN_ET.BR_NET_EVENT_DESK_CHAT
    GameNet._ada._etable[BRNN_CMD.BR_EVENT_DESK_CHAT_V10] =  BRNN_ET.BR_NET_EVENT_DESK_CHAT
end


return ETAdapter