SKEY = {}
SKEY.HOTUPDATE_ENTRY = "updated_hotupdate_entry"
SKEY.UUID = "uuid"
SKEY.UIN = "__uin"
SKEY.OPEN_ID = "__openid"
SKEY.TOKEN = "___token"
SKEY.LOGIN_TYPE = "__login_type"
SKEY.MIGU_TOKEN = "migu_token"
SKEY.SDKACCOUNT_LOGIN = "USER_SDKACCOUNT_LOGIN"
SKEY.FIRST_GAME_FLAG = "_isFirstgame"
SKEY.ZIP_CURRENT_VERSION = "current-version-code"
SKEY.ZIP_CURRENT_CODED_VERSION = "current-version-codezd"
SKEY.ZIP_DOWNLOAD_VERSION = "downloaded-version-code"
SKEY.RES_VERSION = "_resversion"
SKEY.BASE_VERSION = "_baseversion"
SKEY.NEW_FRIEND = "NEWFRIEND"
SKEY.CLOSE_DAY = "closeDay"
SKEY.DEALER_ID = "my_heguan_id"
SKEY.MENU_FLAG_DISABLED = "menu_record_flag_disabled"
SKEY.MENU_CREATE_TIME = "menu_create_time"
SKEY.JPUSH_TAG_1 = "jupsh_tag_1"
SKEY.JPUSH_TAG_2 = "jupsh_tag_2"
SKEY.JPUSH_TAG_3 = "jupsh_tag_3"
SKEY.JPUSH_TIME = "jpush_time_"
SKEY.LABA_SEND_NUM = "sendNum"
SKEY.ACTIVITY_NOTICE_TIMES = "active_notice_times"
SKEY.ACTIVITY_NOTICE_DAY = "active_notice_day"
SKEY.SETTINGS_MUSIC = "MUSIC"
SKEY.SETTINGS_EFFECT = "EFFECT"
SKEY.SETTINGS_SHOCK = "SHOCK"
SKEY.SEND_GIFT_TIP = "BOL_GIVE_GIFT_TIP"
SKEY.SEND_GIFT_TIP_CLOSE_TIME = "send_gift_close_time"
SKEY.VERIFY_CODE = "verify_code"
SKEY.DEFAULT_PAYMETHOD = "default_paymethod"
SKEY.MTT_SETTLE_SHOWED = "mtt_settle_showed" -- mtt排名信息是否显示过
SKEY.MTT_FINAL_TABLE_SHOWED = "mtt_final_table_showed" --mtt进入决赛桌是否提示过
SKEY.MTT_MONEY_SHOWED = "mtt_money_showed" --mtt进入钱圈是否提示过
SKEY.GAME_INSTALL_LIST  = "game_list" --游戏列表
SKEY.REVIEW_STATUS  = "review_status" --游戏列表
SKEY.QUICKSTARTGAME  = "QUICKSTARTGAME" --大厅立即开始游戏选择
SKEY.SERVER_ALLOC_INFO = "RESPONSE" --server_alloc

SKEY.ZJH_GIFTLEAD = "zjh_giftlead"--龙虎斗送礼引导
SKEY.DOMAIN_NAME = "domain_name"
SKEY.ENVIROMENT_TYPE = "enviroment_type"

SKEY.OLD_CHANNEL_NAME  = "old_channel_name" --游戏列表
